// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "0642184c5beeead54427e1fe43a3f941"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"7c72cbc0022f384993ac9c90e1d50f25": "1f8b08000000000000ffec58c18ed33010bde72bac2cc76e0327a49eb920714042e282f6e04da68d97c4313363a042fd7794a48de2c44e53ca6e11ca1e56aae379f366e67926ceaf4888f815a5399432de883867369b2479a24adfb7abeb0a77498672cbf7afdf26edda5dbc6aec54d6b3396e371532e09af2a4543f95a62487a25cd780ad51065ba515ab4a53bc11b57f2162a58965517c6230dda21031ef0dd41eaac72748b9b16fd60d56069015506fb71071edca5909634ce134cf32a01495a9898e1ed6b1236c2f09fe2ee9059e108379d773e0a01f562e132d4bf0513845468c4aefce639091e9d540692e91af05f90e4881bc5e0283608a33213d565501f24c827f483519d22c1082490c8ffc9ae732cb1a4dc8e263588c673323c4613ae1b2b05edc0e5522cafd989e6228e7f1199a0a11974abf3fdabfb9886e65d958f6f2bdeedc9d80a310178749a8385b5910381b11be598550b7c32f9ec3bb0ab716eff1eaad3d44439a1d45bfd7b6091e7f3e747ba742897ab0b1353b94192cad782487a5158761e6b6d05183c9602b6dc18e14434e96163bdaf1c72d1681803f9fe5fc57ea8660095ec8d7323ababf2b4787331588255b5a86c2a8d04d2e0b90f42f9ffde754e98422bbc43c9328ad5eee8d2250da97d2e5507823a8a04a87748dc5ddacbbdc65f3e13fd5fe50091ef50f3a475d890fa0779c77a538818d876640204e35bbc5b15ac2a7277c76fc2fd7137a73cb4990a2e7fd70b6fd57d85f641c7960666aca29f671cc7701ac5a2a27adb47eeaff8d1f5f627d293d7d519b51524ff5ae6b52fda6ec46e15e316fc1ad7fbbf5726b5f746e41adf78ae5cf9abe614ddd511bd0e6e4378643f43b0000ffff381cfec76c160000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("helm.json", packr.Pointer{ForwardBox: gk, ForwardPath: "7c72cbc0022f384993ac9c90e1d50f25"})
	}()

	return nil
}()
